apiVersion: apps/v1
kind: Deployment
metadata:
  name: secureflow-frontend
  namespace: secureflow
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101 # default nginx unprivileged user
      containers:
      - name: frontend
        image: nginxinc/nginx-unprivileged:alpine
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: "300m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: nginx-run
          mountPath: /var/run
        - name: tmp-volume
          mountPath: /tmp
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
      volumes:
      - name: nginx-cache
        emptyDir: {}
      - name: nginx-run
        emptyDir: {}
      - name: tmp-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: secureflow-frontend
  namespace: secureflow
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: frontend
  type: ClusterIP
